using System;
using Packages.Visualizers;
using UnityEngine;
using UnityEngine.UI;

namespace Packages.Data
{
    public class LoadSaveManager : MonoBehaviour
    {
        [Header("LoadSave controls")]
        [SerializeField] private Button loadDataButton;
        [SerializeField] private Button saveDataButton;
        [SerializeField] private Toggle autoGenerateDataToggle;
        
        [Header("DataModel controls")]
        [SerializeField] private DataManager dataManager;
        [SerializeField] private Transform firstListDataModelsVisualizer;
        [SerializeField] private Transform secondListDataModelsVisualizer;
        [SerializeField] private DataModelVisualizer dataModelVisualizerPrefab;
        [SerializeField] private Text firstListDataModelNameText;
        [SerializeField] private Text secondListDataModelNameText;
        private void Start()
        {
            loadDataButton.onClick.AddListener(LoadData);
        }

        private void LoadData()
        {
            InstantiateDataModelVisualizers(dataManager.FirstListDataModel, firstListDataModelsVisualizer, 
                dataManager.FirstListDataModel.ListName, firstListDataModelNameText);
            
            InstantiateDataModelVisualizers(dataManager.SecondListDataModel, secondListDataModelsVisualizer,
                dataManager.SecondListDataModel.ListName, secondListDataModelNameText);
        }

        private void InstantiateDataModelVisualizers(ListDataModel listDataModel, Transform parentContainer,  string listName, Text listNameText)
        {
            foreach (var dataModel in listDataModel.DataModels)
            {
                var tempDataModelVisualizer = Instantiate(dataModelVisualizerPrefab.transform, parentContainer).
                    GetComponent<DataModelVisualizer>();
                
                if(tempDataModelVisualizer!=null)
                    tempDataModelVisualizer.SetDataModel(dataModel);
            }
            
            listNameText.text = listName;
        }

        private void SaveData()
        {
            
        }
        
        
    }
}